# Generated by Django 5.2.8 on 2025-11-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_QR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cliente_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='servicio',
            field=models.CharField(choices=[('facturacion', 'Facturación'), ('servicio_medico', 'Servicio Médico'), ('farmacia', 'Farmacia'), ('general', 'General'), ('historia_clinica', 'Historia Clínica')], max_length=50),
        ),
    ]
