# Generated by Django 5.2.8 on 2025-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_QR', '0003_cliente_turno_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/fotos/'),
        ),
    ]
